title: "Giovanni Saraceno"
description: Research, Software, and Teaching
author: Giovanni Saraceno
url: "https://giovsaraceno.github.io"
baseurl: "/"

markdown: kramdown

# Navigation menu
nav:
  - title: "About Me"
    url: "/about_me/"
  - title: "Research"
    url: "/research/"
  - title: "Software"
    url: "/software/"
  - title: "Publications"
    url: "/publications/"
  - title: "CV"
    url: "/cv/"
