title: "Giovanni Saraceno"
description: "Personal webpage"
theme: jekyll-theme-cayman
author: "Giovanni Saraceno"

# Navigation menu
nav:
  - title: "About Me"
    url: "/about_me/"
  - title: "Research"
    url: "/research/"
  - title: "Teaching"
    url: "/teaching/"
  - title: "Software"
    url: "/software/"
  - title: "Publications"
    url: "/publications/"
  - title: "CV"
    url: "/cv/"
